/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package primefactors;
import java.util.*;

public class PrimeFactors {
    public ArrayList<Integer> findPrimeFactors(int input) {
        ArrayList<Integer> arr = new ArrayList<Integer>();
        if(input == 1)
            return arr;
        arr.add(input);
        return arr;
    }

    public boolean isPrime(int input){
        if (input == 2)
            return true;

        for(int i = input-1; i > 1; i = i-1){
            if(input % i == 0)
                break;
            else
                return true;
        }

        return false;
    }
}
