/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package primefactors;
import java.util.*;

public class PrimeFactors {
    public ArrayList<Integer> findPrimeFactors(int input) {
        ArrayList<Integer> arr = new ArrayList<Integer>();
        int it = input;
        int div = 2;
        if(input == 1)
            return arr;
        if(it % 2 != 0)
            div ++;
        while(it % div == 0) {
            arr.add(div);
            it /= div;
            while(it % div != 0 && it != 1)
                div ++;
        }
        if(it != 1)
            arr.add(it);
        return arr;
    }ß
}
