/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package primefactors;
import java.util.*;

public class PrimeFactors {
    public ArrayList<Integer> findPrimeFactors(int input) {
        ArrayList<Integer> arr = new ArrayList<Integer>();
        if(input == 1)
            return arr;
        arr.add(input);
        return arr;
    }
}
