/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package primefactors;

import org.junit.Test;
import static org.junit.Assert.*;

public class PrimeFactorsTest {
    @Test public void testIfGivenOneReturnsOne() {
        PrimeFactors number = new PrimeFactors();
        assertEquals(1, number.findPrimeFactors(1));
 }
}
